#
#
#

CC =  
CFLAGS =  -I. -I../include/ -I/raid5/apps/fftw-2.1.3/include 

LD = /usr/bin/gcc
LDFLAGS = -O2
LIBS = -lm -L/raid5/apps/fftw-2.1.3/lib

AR = ar
ARFLAGS = rus

OBJECTS =  emfile.o energizer.o tom_rotate3d.o pastes.o cross.o shift.o sort4fftw.o fourfilter.o real_utils.o rotate3d.o

PROGRAM = libtom.a

$(PROGRAM): $(OBJECTS)
	$(AR) $(ARFLAGS) $(PROGRAM) $(OBJECTS)

emfile.o:../include/tom.h
energizer.o:../include/tom.h
tom_rotate3d.o:../include/tom.h
pastes.o:../include/tom.h
cross.o:../include/tom.h
shift.o:../include/tom.h
sort4fftw.o:../include/tom.h
fourfilter.o:../include/tom.h
real_utils.o:../include/tom.h
rotate3d.o:../include/tom.h
