TEMPLATE = app
CONFIG -= qt
QMAKE_CFLAGS += -g
#QMAKE_CC = cc
QMAKE_LINK = gcc
#QMAKE_LFLAGS_SHAPP += -g
#INCLUDEPATH += ../tom 
INCLUDEPATH += ../include
#DEPENDPATH += ../tom
#DEPENDPATH += ../io
LIBS += -L../tom -ltom -L../io -lio -lmpi
LIBS += -lsrfftw -lsfftw
#LIBS += -lrfftw -lfftw
#LIBS += -lprofiler
DESTDIR = ../bin
TARGET = omnimatch.bin
SOURCES = omnimatch.c
